/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2022 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_LKCFERR_H
# define HEADER_LKCFERR_H

# include <openssl/symhacks.h>

# define LKCFerr(f, r) ERR_LKCF_error((f), (r), OPENSSL_FILE, OPENSSL_LINE)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_LKCF_strings(void);
void ERR_unload_LKCF_strings(void);
void ERR_LKCF_error(int function, int reason, char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * LKCF function codes.
 */
# define LKCF_F_LKCF_HW_RSA_PRIV_FUNC                     100
# define LKCF_F_LKCF_HW_RSA_PUB_FUNC                      101
# define LKCF_F_LKCF_INIT                                 102
# define LKCF_F_LKCF_PKEY_ADD                             103
# define LKCF_F_LKCF_RSA_PRIV_DEC                         104
# define LKCF_F_LKCF_RSA_PRIV_ENC                         105
# define LKCF_F_LKCF_RSA_PUB_DEC                          106
# define LKCF_F_LKCF_RSA_PUB_ENC                          107
# define LKCF_F_LKCF_UPLOAD_RSA_PRIVKEY                   108

/*
 * LKCF reason codes.
 */
# define LKCF_R_EACCES                                    100
# define LKCF_R_EFAULT                                    101
# define LKCF_R_EKEYEXPIRED                               102
# define LKCF_R_ENOKEY                                    103
# define LKCF_R_ENOPKG                                    104
# define LKCF_R_INVALID_RSA_KEY                           105
# define LKCF_R_KEYCTL_ADD_FAILURE                        106
# define LKCF_R_LKCF_INVALID_PAYLOAD                      107
# define LKCF_R_PADDING_CHECK_FAILED                      108
# define LKCF_R_PADDING_FAILURE                           109
# define LKCF_R_PKEY_ENCRYPT_ERR                          110
# define LKCF_R_UNKNOWN_PADDING_TYPE                      111

#endif
